root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main.exe ."
  bin = "./tmp/main.exe"
  args_bin = ["--transport", "http", "--addr", "localhost:8080"]
  delay = 1000
  exclude_dir = ["tmp", "bin"]
  exclude_regex = ["_test\\.go"]
  kill_delay = 500

[log]
  time = false
