root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/mcp-ign-nav.exe ./cmd"
bin = "./tmp/mcp-ign-nav.exe"
args_bin = ["--transport", "http", "--addr", "localhost:8080"]
include_ext = ["go", "toml", "env"]
include_dir = ["cmd", "internal"]
exclude_dir = ["tmp", "bin"]
delay = 1000

[log]
time = false

[misc]
clean_on_exit = true
