root = "."
tmp_dir = "tmp"

[build]
  args_bin = ["serve"]
  bin = "./tmp/talk-cli.exe"
  cmd = "go build -o ./tmp/talk-cli.exe ./cmd/cli"
  delay = 1000
  exclude_dir = ["tmp", "bin", "vendor"]
  exclude_regex = ["_test.go$"]
  include_ext = ["go", "md"]
  kill_delay = "1s"
  send_interrupt = true

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
